services:
  app:
    build: .
    container_name: dev-portifolio-ws-backend
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app/src
      - ./src/docs:/app/src/docs
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
