name: doalink-api-ci

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  #verifica se o codigo segue os padroes de escrita.
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint:fix

  #verifica vulnerabilidades nas dependencias do projeto
  grype:
    name: grype
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Scan current project
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "."
          fail-build: false
          output-format: table

  #verifica vulnerabilidades de seguranca no codigo
  bearer:
    name: bearer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          exit-code: 0

  #constroi e publica a imagem do projeto
  
  # docker:
  #   name: Docker build and publish
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint
  #     - grype
  #     - bearer
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Extract metada (tags and labels) for Docker
  #       id: tag
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: wallacestm/portifolio-backend
  #         tags: |
  #           # Se o trigger foi uma tag (ex: v1.0.0), a imagem Docker terá a tag 'v1.0.0'
  #           type=ref,event=tag
  #           # Se o trigger foi um push na branch 'main', a imagem terá duas tags: 'latest' e o hash do commit (ex: f1a2b3c)
  #           type=raw,value=latest,enable={{is_default_branch}}
  #           # Se o trigger foi um pull request, a imagem terá a tag 'PR-numero-do-pr'
  #           type=ref,event=pr,prefix=PR-
  #           type=sha
  #     - name: Build and push Docker Image
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         tags: ${{ steps.tag.outputs.tags }}
  #         labels: ${{ steps.tag.outputs.labels }}
